# Generated by Django 5.1.15 on 2026-03-01 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'ordering': ['-data_fotografia']},
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
